## Week 1 – Monthly Dataset Aggregation
Individual monthly files are combined into unified datasets that span multiple months, enabling trend
analysis over time.

### Objective
Load and concatenate all monthly MLS files from January 2024 through the most recently completed
calendar month into analysis-ready combined datasets.

### Outputs
- Combined sold transactions dataset
- Combined listing data dataset

### Skills Learned
- Multi-file dataset management
- Data aggregation with Pandas
- Preparing time-series datasets for analysis

In [87]:
# This line just hides warning messages so we can focus on the results—but we only use it when we understand what those warnings mean.
import warnings
warnings.filterwarnings("ignore")

# Libraries to help with reading and manipulating data
import pandas as pd
from pathlib import Path

In [88]:
data_path = Path("/Users/sarahbarah3/Desktop/crmls")
save_path = Path("/Users/sarahbarah3/Desktop/crmls/combined")

In [89]:
def read_csv_with_fallback(filepath):
    """Read CSV with UTF-8, fallback to cp1252 if needed."""
    try:
        df = pd.read_csv(filepath, encoding="utf-8")
        return df, "utf-8"
    except UnicodeDecodeError:
        df = pd.read_csv(filepath, encoding="cp1252")
        return df, "cp1252"

### Define lists

In [90]:
listing_files = list(data_path.glob("CRMLSListing*.csv"))
sold_files = list(data_path.glob("CRMLSSold*.csv"))

In [91]:
print(list(data_path.glob("*.csv")))

[PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202404_filled.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202409.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202405.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202411.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202410.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202404.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202408.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202412.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202406.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202407.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/priceratio.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202501_filled.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202601.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202403.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202402.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202602.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202401_filled.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202401.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202603.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202512.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202506.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202406_filled.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202507.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202505.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202511.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202509.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202508.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202510.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202504.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202501.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202503.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202502.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202403_filled.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202503.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202502.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202405_filled.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202509.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202505.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202511.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202510.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202504.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202508.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202512.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202506.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202507.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202602.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202603.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202401.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202403.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202601.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202402.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202412.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202407_filled.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202411.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202409.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/newlistings.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSListing202408.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202410.csv'), PosixPath('/Users/sarahbarah3/Desktop/crmls/CRMLSSold202404.csv')]

### Read and Concateante

In [92]:
full_listing = []
encoding_log = []
row_counts = []

for filepath in listing_files:
    df, encoding_used = read_csv_with_fallback(filepath)

    full_listing.append(df)
    encoding_log.append((filepath, encoding_used))
    row_counts.append(len(df))

# Safety check before concat
if full_listing:
    listing_combined = pd.concat(full_listing, ignore_index=True)
    print("Combined listing shape:", listing_combined.shape)
else:
    print("No listing files were loaded.")

Combined listing shape: (851298, 84)

In [93]:
full_sold = []
encoding_log_sold = []
row_counts_sold = []

for filepath in sold_files:
    df, encoding_used = read_csv_with_fallback(filepath)

    full_sold.append(df)
    encoding_log_sold.append((filepath, encoding_used))
    row_counts_sold.append(len(df))

if full_sold:
    sold_combined = pd.concat(full_sold, ignore_index=True)
    print("Combined sold shape:", sold_combined.shape)
else:
    print("No sold files were loaded.")

Combined sold shape: (658362, 84)

In [94]:
listing_combined.to_csv(save_path / "listing_combined.csv", index=False)
sold_combined.to_csv(save_path / "sold_combined.csv", index=False)

### View the first and last 5 rows of the listing dataset.

In [95]:
listing_combined.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,BuyerAgencyCompensationType,BuyerAgencyCompensation
0,929000.0,1076194146,dianne@drector.com,NaN,NaN,Dianne,Rector,NaN,NaN,16882 Canyon Lane,...,2.0,Huntington Beach Union High,92649,NaN,330.0,1847.0,NaN,16882 Canyon Lane,NaN,NaN
1,999999.0,1076194026,realestateby_denisegarcia@gmail.com,NaN,NaN,Denise,Garcia,NaN,NaN,8720 S 4th Avenue,...,2.0,Inglewood Unified,90305,NaN,0.0,8508.0,NaN,8720 S 4th Avenue,NaN,NaN
2,1400000.0,1076193814,alizabethjames@hotmail.com,NaN,NaN,Alizabeth,James,33.858559,-116.542169,505 E Molino Road,...,2.0,Palm Springs Unified,92262,NaN,NaN,10890.0,NaN,505 E Molino Road,NaN,NaN
3,4998888.0,1076193812,ernieramos62@yahoo.com,NaN,NaN,Ernesto,Ramos,NaN,NaN,3653 Halldale Avenue,...,0.0,NaN,90018,NaN,NaN,6192.0,NaN,3653 Halldale Avenue,NaN,NaN
4,549000.0,1076193525,parsanina@yahoo.com,NaN,NaN,Nina,Parsa,NaN,NaN,1736 N Mcdivitt Avenue,...,2.0,Los Angeles Unified,90221,NaN,0.0,4113.0,NaN,1736 N Mcdivitt Avenue,NaN,NaN

In [96]:
listing_combined.tail()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,BuyerAgencyCompensationType,BuyerAgencyCompensation
851293,25000.0,1061308992,robin@cbborrego.com,NaN,NaN,Robin,Reynolds,33.273002,-115.953189,1102 Stanford Avenue,...,NaN,NaN,92274,NaN,0.0,13503.6,NaN,1102 Stanford Avenue,NaN,NaN
851294,625000.0,1060129455,joel@ripfritzer.com,NaN,NaN,Joel,Cloud,32.773679,-116.933649,1725 Grove Road,...,NaN,NaN,92020,NaN,0.0,43560.0,NaN,1725 Grove Road,NaN,NaN
851295,409000.0,1058408504,marierealtor4you@gmail.com,NaN,NaN,Marie,Arredondo,33.207200,-116.299900,3135 Club Circle East,...,2.0,Borrego Springs Unified,92004,NaN,0.0,34848.0,NaN,3135 Club Circle East,NaN,NaN
851296,3900000.0,1038675566,brettbman@gmail.com,NaN,NaN,Brett,Baumann,37.497693,-120.046471,665 Acs. - Mt Bullion Cut-Off Road,...,NaN,NaN,95338,NaN,0.0,28980903.6,NaN,665 Acs. - Mt Bullion Cut-Off Road,NaN,NaN
851297,1825000.0,1038248402,taylor@willisallen.com,NaN,NaN,Taylor,Smith,32.617947,-117.134345,5 Bridgetown Bend,...,2.0,Coronado Unified,92118,NaN,331.0,3959.0,NaN,5 Bridgetown Bend,NaN,NaN

### View the first and last 5 rows of the sold dataset.

In [97]:
sold_combined.head()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled,BuyerAgentAOR,ListAgentAOR,OriginatingSystemName,OriginatingSystemSubName
0,NaN,True,NaN,NaN,NaN,159000.0,555125771,deborah.potestio@c21selectgroup.com,2024-04-29,45000.0,...,95916,0.0,336283.2,NaN,False,False,NaN,NaN,NaN,NaN
1,NaN,True,NaN,NaN,NaN,144000.0,554271746,crchapman@sbcglobal.net,2024-04-26,78000.0,...,95966,0.0,101495.0,NaN,False,False,NaN,NaN,NaN,NaN
2,NaN,True,NaN,NaN,False,265000.0,543251400,michaelg@londonproperties.com,2024-04-02,250000.0,...,93726,0.0,8100.0,NaN,False,False,NaN,NaN,NaN,NaN
3,NaN,True,NaN,NaN,NaN,925000.0,539236677,chris.campbell@msn.com,2024-04-10,815000.0,...,92223,0.0,564988.0,NaN,False,False,NaN,NaN,NaN,NaN
4,NaN,True,NaN,NaN,NaN,25000.0,538449222,rrinder@sbcglobal.net,2024-04-06,15000.0,...,95966,0.0,6098.0,NaN,False,False,NaN,NaN,NaN,NaN

In [98]:
sold_combined.tail()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled,BuyerAgentAOR,ListAgentAOR,OriginatingSystemName,OriginatingSystemSubName
658357,NaN,NaN,NaN,NaN,NaN,649000.0,1008475397,chiggamasta424@gmail.com,2024-04-22,450000.0,...,90805,NaN,4682.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658358,NaN,True,NaN,NaN,NaN,75689.0,1003434877,jhisquierdo@lee-associates.com,2024-04-03,75689.0,...,92371,NaN,946123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658359,NaN,True,NaN,NaN,NaN,275000.0,1002713752,MLS@DaltonRealtors.com,2024-04-19,100000.0,...,92082,0.0,619859.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658360,NaN,False,NaN,NaN,False,10000.0,1002447928,Tazzie@CoronadoPremierProperties.com,2024-04-05,8300.0,...,92118,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658361,NaN,True,NaN,NaN,NaN,1600000.0,1001660596,diana@countryqueen.com,2024-04-03,1050000.0,...,91765,294.0,52212.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Overview of the dataset shape (Listing)

In [99]:
# checking the shape of the data
print(f"There are {sold_combined.shape[0]} rows and {sold_combined.shape[1]} columns in combined listing data.")  # f-string

There are 658362 rows and 84 columns in combined listing data.

### Overview of the dataset shape (Sold)

In [100]:
# checking the shape of the data
print(f"There are {sold_combined.shape[0]} rows and {sold_combined.shape[1]} columns in Feb data.")  # f-string

There are 658362 rows and 84 columns in Feb data.

### View Listing dataset columns

In [101]:
listing_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851298 entries, 0 to 851297
Data columns (total 84 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             847979 non-null  float64
 1   ListingKey                    851298 non-null  int64
 2   ListAgentEmail                778717 non-null  object
 3   CloseDate                     267472 non-null  object
 4   ClosePrice                    245327 non-null  float64
 5   ListAgentFirstName            846325 non-null  object
 6   ListAgentLastName             851219 non-null  object
 7   Latitude                      739421 non-null  float64
 8   Longitude                     740124 non-null  float64
 9   UnparsedAddress               849175 non-null  object
 10  PropertyType                  851298 non-null  object
 11  LivingArea                    744957 non-null  float64
 12  ListPrice                     849168 non-null  float64
 13  DaysOnMarket                  851298 non-null  int64
 14  ListOfficeName                851298 non-null  object
 15  BuyerOfficeName               257219 non-null  object
 16  CoListOfficeName              170681 non-null  object
 17  ListAgentFullName             851067 non-null  object
 18  CoListAgentFirstName          170046 non-null  object
 19  CoListAgentLastName           170532 non-null  object
 20  BuyerAgentMlsId               258898 non-null  object
 21  BuyerAgentFirstName           258736 non-null  object
 22  BuyerAgentLastName            259685 non-null  object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       245707 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             851298 non-null  int64
 27  MLSAreaMajor                  755268 non-null  object
 28  TaxAnnualAmount               6056 non-null    float64
 29  CountyOrParish                851297 non-null  object
 30  PropertyType.1                851298 non-null  object
 31  MlsStatus                     851298 non-null  object
 32  ElementarySchool              79167 non-null   object
 33  ListAgentFirstName.1          846325 non-null  object
 34  AttachedGarageYN              561191 non-null  object
 35  ParkingTotal                  798952 non-null  float64
 36  BuilderName                   29273 non-null   object
 37  PropertySubType               747330 non-null  object
 38  LotSizeAcres                  770129 non-null  float64
 39  SubdivisionName               284555 non-null  object
 40  BuyerOfficeAOR                244443 non-null  object
 41  YearBuilt                     781907 non-null  float64
 42  DaysOnMarket.1                851298 non-null  int64
 43  StreetNumberNumeric           847566 non-null  float64
 44  LivingArea.1                  744957 non-null  float64
 45  ListingId                     851298 non-null  object
 46  BathroomsTotalInteger         781396 non-null  float64
 47  City                          850332 non-null  object
 48  TaxYear                       870 non-null     float64
 49  BuildingAreaTotal             136250 non-null  float64
 50  BedroomsTotal                 748352 non-null  float64
 51  ContractStatusChangeDate      844531 non-null  object
 52  Longitude.1                   740124 non-null  float64
 53  ElementarySchoolDistrict      0 non-null       float64
 54  CoBuyerAgentFirstName         20769 non-null   object
 55  PurchaseContractDate          377669 non-null  object
 56  ListingContractDate           851298 non-null  object
 57  BelowGradeFinishedArea        3418 non-null    float64
 58  BusinessType                  5974 non-null    object
 59  Latitude.1                    739421 non-null  float64
 60  ListPrice.1                   849168 non-null  float64
 61  StateOrProvince               851222 non-null  object
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          79280 non-null   object
 64  FireplaceYN                   728943 non-null  object
 65  Stories                       631000 non-null  float64
 66  HighSchool                    104237 non-null  object
 67  Levels                        688238 non-null  object
 68  ListAgentLastName.1           851219 non-null  object
 69  CloseDate.1                   267472 non-null  object
 70  LotSizeDimensions             48514 non-null   object
 71  LotSizeArea                   773895 non-null  float64
 72  MainLevelBedrooms             394562 non-null  float64
 73  NewConstructionYN             736724 non-null  object
 74  GarageSpaces                  689741 non-null  float64
 75  HighSchoolDistrict            513073 non-null  object
 76  PostalCode                    851089 non-null  object
 77  BuyerOfficeName.1             257219 non-null  object
 78  AssociationFee                576736 non-null  float64
 79  LotSizeSquareFeet             772817 non-null  float64
 80  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 81  UnparsedAddress.1             849175 non-null  object
 82  BuyerAgencyCompensationType   123538 non-null  object
 83  BuyerAgencyCompensation       123519 non-null  float64
dtypes: float64(32), int64(4), object(48)
memory usage: 545.6+ MB

### View Sold dataset columns

In [102]:
sold_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 658362 entries, 0 to 658361
Data columns (total 84 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Flooring                      386217 non-null  object
 1   ViewYN                        592663 non-null  object
 2   WaterfrontYN                  361 non-null     object
 3   BasementYN                    10767 non-null   object
 4   PoolPrivateYN                 574581 non-null  object
 5   OriginalListPrice             656437 non-null  float64
 6   ListingKey                    658362 non-null  int64
 7   ListAgentEmail                614258 non-null  object
 8   CloseDate                     658362 non-null  object
 9   ClosePrice                    658355 non-null  float64
 10  ListAgentFirstName            654430 non-null  object
 11  ListAgentLastName             658290 non-null  object
 12  Latitude                      639047 non-null  float64
 13  Longitude                     639238 non-null  float64
 14  UnparsedAddress               657332 non-null  object
 15  PropertyType                  658362 non-null  object
 16  LivingArea                    611430 non-null  float64
 17  ListPrice                     657360 non-null  float64
 18  DaysOnMarket                  658362 non-null  int64
 19  ListOfficeName                658362 non-null  object
 20  BuyerOfficeName               650108 non-null  object
 21  CoListOfficeName              140192 non-null  object
 22  ListAgentFullName             658189 non-null  object
 23  CoListAgentFirstName          135379 non-null  object
 24  CoListAgentLastName           135661 non-null  object
 25  BuyerAgentMlsId               656400 non-null  object
 26  BuyerAgentFirstName           655373 non-null  object
 27  BuyerAgentLastName            657984 non-null  object
 28  FireplacesTotal               0 non-null       float64
 29  AssociationFeeFrequency       194952 non-null  object
 30  AboveGradeFinishedArea        0 non-null       float64
 31  ListingKeyNumeric             658362 non-null  int64
 32  MLSAreaMajor                  586233 non-null  object
 33  TaxAnnualAmount               2842 non-null    float64
 34  CountyOrParish                658362 non-null  object
 35  MlsStatus                     658362 non-null  object
 36  ElementarySchool              73168 non-null   object
 37  AttachedGarageYN              475867 non-null  object
 38  ParkingTotal                  636779 non-null  float64
 39  BuilderName                   25333 non-null   object
 40  PropertySubType               607278 non-null  object
 41  LotSizeAcres                  595429 non-null  float64
 42  SubdivisionName               232217 non-null  object
 43  BuyerOfficeAOR                630836 non-null  object
 44  YearBuilt                     630247 non-null  float64
 45  BuyerAgencyCompensationType   133531 non-null  object
 46  StreetNumberNumeric           656695 non-null  float64
 47  ListingId                     658362 non-null  object
 48  BathroomsTotalInteger         627469 non-null  float64
 49  City                          657846 non-null  object
 50  BuyerAgencyCompensation       133596 non-null  float64
 51  TaxYear                       413 non-null     float64
 52  BuildingAreaTotal             84995 non-null   float64
 53  BedroomsTotal                 614019 non-null  float64
 54  ContractStatusChangeDate      656933 non-null  object
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         53432 non-null   object
 57  PurchaseContractDate          645258 non-null  object
 58  ListingContractDate           658268 non-null  object
 59  BelowGradeFinishedArea        2817 non-null    float64
 60  BusinessType                  1847 non-null    object
 61  StateOrProvince               658362 non-null  object
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          73698 non-null   object
 64  FireplaceYN                   600209 non-null  object
 65  Stories                       525101 non-null  float64
 66  HighSchool                    95936 non-null   object
 67  Levels                        566302 non-null  object
 68  LotSizeDimensions             34353 non-null   object
 69  LotSizeArea                   597522 non-null  float64
 70  MainLevelBedrooms             348375 non-null  float64
 71  NewConstructionYN             580050 non-null  object
 72  GarageSpaces                  573803 non-null  float64
 73  HighSchoolDistrict            438967 non-null  object
 74  PostalCode                    658177 non-null  object
 75  AssociationFee                454281 non-null  float64
 76  LotSizeSquareFeet             597007 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  latfilled                     161667 non-null  object
 79  lonfilled                     161667 non-null  object
 80  BuyerAgentAOR                 519693 non-null  object
 81  ListAgentAOR                  524439 non-null  object
 82  OriginatingSystemName         77869 non-null   object
 83  OriginatingSystemSubName      77869 non-null   object
dtypes: float64(28), int64(3), object(53)
memory usage: 421.9+ MB

### View column counts (Listing)

In [103]:
listing_combined.PropertyType.value_counts()

PropertyType
Residential            539213
ResidentialLease       177543
Land                    56333
ResidentialIncome       31571
ManufacturedInPark      24483
CommercialSale          11696
CommercialLease          7725
BusinessOpportunity      2734
Name: count, dtype: int64

### View column counts (Sold)

In [104]:
sold_combined.PropertyType.value_counts()

PropertyType
Residential            442285
ResidentialLease       150415
Land                    21927
ManufacturedInPark      18004
ResidentialIncome       17628
CommercialSale           4147
CommercialLease          3494
BusinessOpportunity       462
Name: count, dtype: int64

### Filter PropertyType to Residential only
We’re filtering the dataset to only include residential properties so we can analyze the deals that actually matter to us.

### Create new datasets

In [105]:
listing_residential_df = listing_combined[listing_combined["PropertyType"] == "Residential"]
sold_residential_df = sold_combined[sold_combined["PropertyType"] == "Residential"]

### Show row and column counts after the Residential filter

In [106]:
# checking the shape of the data
print(f"There are {listing_residential_df.shape[0]} rows and {listing_residential_df.shape[1]} columns in listing data for residential only.")  # f-string
print(f"There are {sold_residential_df.shape[0]} rows and {sold_residential_df.shape[1]} columns in sold data for residential only.")  # f-string

There are 539213 rows and 84 columns in listing data for residential only.
There are 442285 rows and 84 columns in sold data for residential only.

### Save new datasets to CSVs (residential only)

In [107]:
listing_residential_df.to_csv(save_path / "listings_residential_properties.csv", index=False)
sold_residential_df.to_csv(save_path / "sold_residential_properties.csv", index=False)